# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8149b77b83773ada836f1326090f805cf2d2701d8f98d7978bbed402bfc303e146af417e18e5cfc884d71ba260c919114c53be1f1e2831408f15441f6fe7dcd3

test:
  secret_key_base: a51e46539d5eae6f9c29b7fe0a6cf720845192cfc004078df05e00f48ad5c0f30e1ca4bd3112051a0b4a79afd5016365a4411c766291a7baa65a2fbc3d4ddb13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
